version: '3.8'
services:
  mysql-db:
    container_name: class-administration-mysql-db
    image: mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    ports:
      - "${MYSQL_PORT_EXPOSE}:3306"
  nestjs-app:
    container_name: class-administration-api
    build: .
    env_file: ./.env
    depends_on:
      mysql-db:
        condition: service_healthy
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"